[package]
name = "rsynko-media"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "Media download meaning for Rsynko"
documentation = "https://docs.rs/rsynko-media"
readme = "README.md"
keywords.workspace = true
categories.workspace = true

[dependencies]
ambassador.workspace = true
alux-ext.workspace = true
anyhow.workspace = true
alux-sdk.workspace = true
derive-new.workspace = true
derive_more.workspace = true
itertools.workspace = true
thiserror.workspace = true
rsynko-download.workspace = true

[lints]
workspace = true
