[package]
name = "rsynko-download"
version = "0.1.2"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "Meaning-first resource download specification for Rsynko"
documentation = "https://docs.rs/rsynko-download"
readme = "README.md"
keywords.workspace = true
categories.workspace = true

[dependencies]
ambassador.workspace = true
anyhow.workspace = true
alux-ext.workspace = true
alux-sdk.workspace = true
derive-new.workspace = true
thiserror.workspace = true

[lints]
workspace = true
