[package]
name = "rsynko-manager"
version = "0.1.1"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "Renderer-neutral transfer-manager specification for Rsynko"
documentation = "https://docs.rs/rsynko-manager"
readme = "README.md"
keywords.workspace = true
categories.workspace = true

[dependencies]
ambassador.workspace = true
anyhow.workspace = true
alux-sdk.workspace = true
alux-ext.workspace = true
rsynko-media.workspace = true
rsynko-session.workspace = true

[lints]
workspace = true
