[package]
name = "rsynko"
version = "0.1.2"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "Command-line and terminal application for retrieving and transferring sources"
documentation = "https://github.com/tgrospic/rsynko"
readme = "README.md"
keywords.workspace = true
categories.workspace = true

[[bin]]
name = "rsynko"
path = "src/main.rs"

[dependencies]
clap.workspace = true
rsynko-manager.workspace = true
rsynko-media.workspace = true
rsynko-memory.workspace = true
rsynko-process.workspace = true
rsynko-ratatui.workspace = true
rsynko-reqwest.workspace = true
rsynko-rsync.workspace = true
rsynko-yt.workspace = true

[dev-dependencies]
rsynko-reqwest.workspace = true
tempfile.workspace = true

[lints]
workspace = true
