[package]
name = "rsynko-yt"
version = "0.1.1"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "Youtube download specialization for Rsynko"
documentation = "https://docs.rs/rsynko-yt"
readme = "README.md"
keywords.workspace = true
categories.workspace = true

[dependencies]
ambassador.workspace = true
anyhow.workspace = true
alux-ext.workspace = true
thiserror.workspace = true
rsynko-download.workspace = true
rsynko-media.workspace = true

[lints]
workspace = true
