[package]
name = "rsynko-ui"
version = "0.1.2"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "Renderer-neutral presentation specification for Rsynko"
documentation = "https://docs.rs/rsynko-ui"
readme = "README.md"
keywords.workspace = true
categories.workspace = true

[dependencies]
anyhow.workspace = true
alux-ext.workspace = true
rsynko-manager.workspace = true

[lints]
workspace = true
