[package]
name = "rsynko-x"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Specification of the media one public tweet carries"
documentation = "https://docs.rs/rsynko-x"
readme = "README.md"
keywords.workspace = true
categories.workspace = true

[dependencies]
ambassador.workspace = true
anyhow.workspace = true
alux-ext.workspace = true
alux-sdk.workspace = true

[lints]
workspace = true
